name: sonat_hrm_rewarded
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  collection: ^1.18.0
  dio: ^5.4.2
  equatable: ^2.0.5
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  firebase_storage: ^12.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_colorpicker: ^1.0.3
  flutter_dotenv: ^5.1.0
  flutter_form_builder: ^9.3.0
  flutter_local_notifications: ^17.2.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  fluttertoast: ^8.2.6
  form_builder_validators: ^11.0.0
  formz: ^0.7.0
  get: ^4.6.6
  go_router: ^14.2.0
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  logger: ^2.4.0
  meta: ^1.11.0
  package_info_plus: ^8.0.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.2
  skeletonizer: ^1.4.2
  substring_highlight: ^1.0.33
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - .env.development
    - .env.production

    # Add assets from the images directory to the application.
    - assets/images/

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#ffffff"
  image: assets/images/sonat_logo.jpg

  android_12:
    image: assets/images/sonat_logo.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/sonat_logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
